# Generated by Django 5.2.17 on 2026-09-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=150)),
                ('confirmpassword', models.CharField(max_length=150)),
            ],
        ),
    ]
